// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/globe": {
    params: {};
  };
  "/country/:code": {
    params: {
      "code": string;
    };
  };
  "/speech/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/search" | "/globe" | "/country/:code" | "/speech/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/globe.tsx": {
    id: "routes/globe";
    page: "/globe";
  };
  "routes/country.$code.tsx": {
    id: "routes/country.$code";
    page: "/country/:code";
  };
  "routes/speech.$id.tsx": {
    id: "routes/speech.$id";
    page: "/speech/:id";
  };
};