-- Create letters table for storing diplomatic letters generated by the AI agent
CREATE TABLE IF NOT EXISTS letters (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    content TEXT NOT NULL,
    addressed_to TEXT NOT NULL,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    subject TEXT,
    metadata TEXT -- JSON field for additional metadata like country_code, session, etc.
);

-- Create index for better query performance
CREATE INDEX IF NOT EXISTS idx_letters_addressed_to ON letters(addressed_to);
CREATE INDEX IF NOT EXISTS idx_letters_date_created ON letters(date_created);
